from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from operatekit.core.target.target import TargetSpec
from operatekit.core.ui.locator import Locator


@runtime_checkable
class SurfaceDriver(Protocol):
    def launch(self, target: TargetSpec | None = None, *, stop: bool = False) -> None: ...
    def close(self) -> None: ...
    def click(self, locator: Locator, *, timeout: float = 10) -> None: ...
    def type_text(self, text: str, *, locator: Locator | None = None, clear: bool = False, timeout: float = 10) -> None: ...
    def press_key(self, key: str) -> None: ...
    def exists(self, locator: Locator, *, timeout: float = 0) -> bool: ...
    def wait_visible(self, locator: Locator, *, timeout: float = 10) -> None: ...
    def scroll(self, direction: str = "down", *, amount: float = 0.8) -> None: ...
    def get_tree(self) -> str: ...
    def screenshot(self, path: str | Path) -> Path: ...
